# Generated by Django 4.1.7 on 2023-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('ph', models.IntegerField()),
                ('pwd', models.CharField(max_length=12)),
                ('cpwd', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
