# Generated by Django 4.1.7 on 2023-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_signup1_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=12)),
                ('cpassword', models.CharField(max_length=12)),
            ],
        ),
    ]
