# Generated by Django 4.1.7 on 2023-03-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_signup2'),
    ]

    operations = [
        migrations.CreateModel(
            name='org_pg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20)),
                ('email1', models.CharField(max_length=40)),
                ('mobile1', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('etype', models.CharField(max_length=20)),
                ('eloc', models.CharField(max_length=100)),
                ('etheme', models.CharField(max_length=60)),
                ('ereq', models.CharField(max_length=100)),
                ('ebudget', models.IntegerField()),
                ('ebreak', models.IntegerField()),
            ],
        ),
    ]
