# Generated by Django 4.1.7 on 2023-03-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_org_pg1'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_pg1',
            name='eservice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org_pg1',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='org_pg1',
            name='ref',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='org_pg1',
            name='etype',
            field=models.BooleanField(default=False),
        ),
    ]
