# Generated by Django 4.1.7 on 2023-03-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_org_pg1_eservice_alter_org_pg1_etype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_pg1',
            name='eservice',
            field=models.CharField(choices=[('Event Planning', 'Event Planning'), ('Event Coordination', 'Event Coordination'), ('Event Design', 'Event Design'), ('Event Production', 'Event Production'), ('Other', 'Other')], default='Event Planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='org_pg1',
            name='etype',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Social', 'Social'), ('Other', 'Other')], default='Corporate', max_length=20),
        ),
    ]
