# Generated by Django 4.1.7 on 2023-03-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_org_pg1_eservice_alter_org_pg1_etype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='org_pg1',
            new_name='organizers',
        ),
    ]
