# Generated by Django 4.1.7 on 2023-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_rename_org_pg1_organizers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizers',
            name='eservice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizers',
            name='etype',
            field=models.CharField(max_length=100),
        ),
    ]
