# Generated by Django 4.1.7 on 2023-03-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_organizers_eservice_alter_organizers_etype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizers',
            old_name='name1',
            new_name='name',
        ),
    ]
