# Generated by Django 4.1.7 on 2023-03-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_rename_name1_organizers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizers',
            old_name='name',
            new_name='name1',
        ),
    ]
