# Generated by Django 4.1.7 on 2023-04-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_rename_name_organizers_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizers',
            name='epic',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
