# Generated by Django 4.1.7 on 2023-04-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_organizers_epic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizers',
            name='epic',
        ),
    ]
