# Generated by Django 4.1.7 on 2023-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_organizers_epic'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=20)),
                ('gcount', models.IntegerField()),
                ('addreq', models.CharField(max_length=100)),
            ],
        ),
    ]
