# Generated by Django 4.1.7 on 2023-04-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.signup2'),
            preserve_default=False,
        ),
    ]
