# Generated by Django 4.1.7 on 2023-04-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='email',
        ),
    ]
