# Generated by Django 4.1.7 on 2023-04-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_rename_name_book_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
