# Generated by Django 4.1.7 on 2023-04-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_remove_book_email_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
    ]
