# Generated by Django 4.1.7 on 2023-04-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_remove_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.signup2'),
        ),
    ]
