# Generated by Django 4.1.7 on 2023-04-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_book_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup2',
            old_name='uname',
            new_name='name',
        ),
    ]
