# Generated by Django 4.1.7 on 2023-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_rename_uname_signup2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup2',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
