# Generated by Django 4.1.7 on 2023-04-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_alter_signup2_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup2',
            old_name='name',
            new_name='uname',
        ),
    ]
