# Generated by Django 4.1.7 on 2023-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_rename_name_signup2_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup2',
            name='uname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
